name: Dump Database

on:
  push:
    paths:
      - "db/**"
  workflow_dispatch:

jobs:
  dump-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dump tables to SQL
        uses: ryohidaka/action-dump-sqlite@v0.1.0
        with:
          db: "db/saizeriya.db"
          output: "db/saizeriya.sql"

      - name: Commit and push changes
        uses: ryohidaka/action-commit-push@v0.3.2
        with:
          files: "db/saizeriya.sql"
          commit-message: "chore: Update dump file"
          rebase: true
