name: Update

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "db/**"
      - "tools/converter/**"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.3"
          check-latest: true
          cache-dependency-path: |
            tools/converter/go.sum

      - name: Restore DB
        uses: ryohidaka/action-restore-sqlite@v0.1.0
        with:
          db: "db/saizeriya.db"
          dump-file: "db/saizeriya.sql"

      - name: Update files
        run: cd tools/converter && go run cmd/main.go --csv --json --md

      - name: Commit and push changes
        uses: ryohidaka/action-commit-push@v0.6.0
        with:
          files: "saizeriya.csv saizeriya.json saizeriya.md"
          commit-message: "chore: Update files"
          rebase: true
